# Generated by Django 5.2.3 on 2025-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AddField(
            model_name="book",
            name="book_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
